# Generated by Django 4.1.4 on 2023-01-19 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_Name', models.CharField(max_length=50)),
                ('Stu_Password', models.CharField(max_length=50)),
                ('Stu_Pno', models.BigIntegerField()),
                ('Stu_Semester', models.CharField(max_length=50)),
                ('Stu_Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=50)),
                ('Author_Name', models.CharField(max_length=50)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.course')),
            ],
        ),
    ]
