# Generated by Django 4.1.4 on 2023-01-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author_Name',
            new_name='AuthorName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Book_Name',
            new_name='BookName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Course',
            new_name='Course_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_Name',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_Pno',
            new_name='Pno',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_Password',
            new_name='Semester',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_Semester',
            new_name='StudentName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_Course',
            new_name='course_id',
        ),
        migrations.CreateModel(
            name='Issue_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Book_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.book')),
                ('Student_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.student')),
            ],
        ),
    ]
