# Generated by Django 4.1.4 on 2023-01-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_rename_author_name_book_authorname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='AuthorName',
            new_name='Author_Name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='BookName',
            new_name='Book_Name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Course_id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Course_Name',
            new_name='course_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='Semester',
            field=models.IntegerField(),
        ),
    ]
